name: Weekly Commit Report

on:
  schedule:
    - cron: '30 10 * * 5'  # This sets the workflow to run at 10:00 UTC+8 every Friday (6 PM Beijing time)
  workflow_dispatch:  # This allows you to manually trigger the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive
          fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run the script
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        ORG_NAME: HITSZ-OpenAuto
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Add your OpenAI API key as a secret
      run: |
        python scripts/weekly.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'content'
        default_author: github_actions
